#!/usr/bin/env bash
VM=${1:-$(basename $(pwd))}
if [ ! -e "$HOME/Documents/Virtual Machines.localized/$VM.vmwarevm" ]; then
    exit 1
fi

if vmrun list | grep -q $VM.vmwarevm; then
  echo "running"
else
  echo "stopped"
fi
