#!/usr/bin/env bash
VM=${1:-$(basename $(pwd))}
STATE=${2:-base}
if ! VBoxManage list vms | grep $VM; then
    STATE=$VM
    VM=$(basename $(pwd))
fi
vmrun deleteSnapshot "$HOME/Documents/Virtual Machines.localized/$VM.vmwarevm" bak
vmrun snapshot "$HOME/Documents/Virtual Machines.localized/$VM.vmwarevm" bak
vmrun revertToSnapshot "$HOME/Documents/Virtual Machines.localized/$VM.vmwarevm" $STATE
