#!/usr/bin/env bash
VM=${1:-$(basename $(pwd))}
STATE=${2:-base}
if ! powervm $VM >/dev/null; then
    STATE=$VM
    VM=$(basename $(pwd))
fi
vmrun snapshot "$HOME/Documents/Virtual Machines.localized/$VM.vmwarevm" $STATE
