#!/usr/bin/env bash
VM=${1:-$(basename $(pwd))}
vmrun revertToSnapshot "$HOME/Documents/Virtual Machines.localized/$VM.vmwarevm" bak
vmrun deleteSnapshot "$HOME/Documents/Virtual Machines.localized/$VM.vmwarevm" bak
